-- LiquiTrace Database Schema
-- Run this in the Supabase SQL Editor

-- 1. Create the signals table
create table if not exists public.signals (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  -- Token Data
  token_address text not null unique,
  pair_address text not null,
  token_name text,
  token_summary text,
  
  -- Market Data
  liquidity_eth numeric, -- Actually stores USD value
  initial_price numeric,
  price_change_pct numeric default 0,
  volume_24h numeric default 0,
  market_cap numeric default 0,
  
  -- Links
  swap_link text,
  dex_url text
);

-- 2. Create index for faster lookups/sorting if needed
create index if not exists signals_token_address_idx on public.signals (token_address);
create index if not exists signals_updated_at_idx on public.signals (updated_at);

-- 3. Enable Row Level Security (RLS) - Optional but recommended
alter table public.signals enable row level security;

-- 4. Create Policy: Allow public read access (for the frontend)
create policy "Allow public read access"
  on public.signals for select
  using ( true );

-- 5. Create Policy: Allow service role write access (for the bot)
-- Service role bypasses RLS, but explicit policy is good practice
create policy "Allow service role full access"
  on public.signals for all
  using ( true )
  with check ( true );
